### ISSUE TITLE
only WebView ? 

### ISSUE THREAD

**Issue by manigopal** [iamarbaazkhan/Wordpress-rest-api-app#1]
Hi @iamarbaazkhan 

Nice App But some options missing ,

1. Categories list in Navigation Drawer (Menus)
2. Post(s) Featured image not shown in Post Detail Page
3. Images shown at Landing page can be aligned to Left or Right
4. Page Navigation like 1,2,3 limit of posts can be set to 25 OR any.

Mainly the URL have been replaced still the old data is shown.,

Also update repositories / libraries & fix depreciated ones

Snapshot of the App Screens (Flow & Main)

only WebView of datas are loaded., make them fetch using Wordpress API

**Comment by iamarbaazkhan** [comment]
Thank you for showing interest in this project and yeah there are many work
is left to be completed in this project if you want to make some changes go
on and I have made this project open sourced .
